export const calculatorConfig = [
  {
    name: "industry",
    type: "select",
    title: "Отрасль",
    label: "Область производства",
    placeholder: "Выберите из списка",
    description:
      "Создания нового или развитии существующего промышленного производства",
  },
  {
    name: "counter",
    type: "input",
    label: "Число сотрудников, чел",
    placeholder: "100",
    title: "Штатная численность сотрудников,чел",
  },
  {
    name: "average",
    type: "input",
    label: "Заработная плата, руб",
    placeholder: "100",
    title: "Средняя заработная плата",
  },
  {
    name: "legalForm",
    type: "radio",
    title: "Организационно-правовая форма",
  },
  {
    name: "taxType",
    type: "radio",
    title: "Тип налогооблажения",
  },
  {
    name: "maps",
    title: "Район",
  },
  {
    name: "area",
    type: "input",
    title: "Площадь земельного участка, м. кв.",
    label: "Площадь, м.кв",
    placeholder: "10 000",
  },
  {
    name: "object",
    name1: "typeBuild",
    name2: "squareBuild",
    type: "multitext",
    title: "Тип и площадь объектов недвижимости",
    label1: "Тип здания",
    label2: "Площадь, м.кв.",
    placeholder1: "Введите ключевое слово",
    placeholder2: "1 000",
  },
  {
    name: "capital",
    name1: "capitalType",
    name2: "capitalSquare",
    type: "multitext",
    title: "Иные капитальные сооружения",
    label1: "Тип здания",
    label2: "Площадь, м.кв.",
    placeholder1: "Введите ключевое слово",
    placeholder2: "1 000",
  },
  {
    name: "equipment",
    name1: "equipmentType",
    name2: "equipmentQuantity",
    name3: "equipmentCount",
    type: "multiselect",
    title: "Оборудование",
    label1: "Тип оборудования",
    label2: "Кол-во, шт",
    label3: "Цена",
    placeholder1: "Введите или выберите из списка",
    placeholder2: "1",
    placeholder3: "1 000 000",
  },
  {
    name: "other",
    name1: "otherType",
    name2: "otherSquare",
    type: "multiother",
    title: "Иные потребности",
    label1: "Тип здания",
    label2: "Площадь, м.кв.",
    placeholder1: "Иное 1",
    placeholder2: "200",
  },
];
